In [3]:
import pandas as pd
import numpy as np

In [4]:
hourly=pd.read_csv("hourly_power_features.csv")
hourly["Datetime"] = pd.to_datetime(hourly["Datetime"])
hourly = hourly.set_index("Datetime")

hourly.head()

,Global_active_power_mean,Global_active_power_max,Global_active_power_min,Global_active_power_std,Voltage_mean,Voltage_max,Voltage_min,Voltage_std,Global_intensity_mean,Global_intensity_max,...,Sub_metering_1_min,Sub_metering_1_std,Sub_metering_2_mean,Sub_metering_2_max,Sub_metering_2_min,Sub_metering_2_std,Sub_metering_3_mean,Sub_metering_3_max,Sub_metering_3_min,Sub_metering_3_std
Datetime,,,,,,,,,,,,,,,,,,,,,
2006-12-16 17:00:00,4.188278,7.026,2.472,1.070610,234.643889,237.14,230.98,1.528529,18.100000,33.2,...,0.0,0.0,0.527778,2.0,0.0,0.696362,16.861111,18.0,16.0,0.424451
2006-12-16 18:00:00,3.598283,6.752,2.188,1.132717,234.580167,238.28,231.85,1.623576,15.600000,29.0,...,0.0,0.0,6.716667,37.0,0.0,11.830858,16.866667,18.0,16.0,0.468198
2006-12-16 19:00:00,3.400233,4.070,3.202,0.135354,233.232500,235.12,231.57,0.901678,14.503333,17.4,...,0.0,0.0,1.433333,5.0,0.0,1.253695,16.683333,17.0,16.0,0.469102
2006-12-16 20:00:00,3.268567,3.496,1.832,0.264286,234.071500,237.54,231.95,1.483866,13.916667,14.8,...,0.0,0.0,0.000000,0.0,0.0,0.000000,16.783333,18.0,16.0,0.454420
2006-12-16 21:00:00,3.056467,3.502,1.692,0.576796,237.158667,239.69,235.73,0.862382,13.046667,14.8,...,0.0,0.0,0.416667,2.0,0.0,0.696034,17.216667,18.0,17.0,0.415450

In [5]:
hour = hourly.index.hour
hourly["hour_sin"] = np.sin(2 * np.pi * hour / 24)
hourly["hour_cos"] = np.cos(2 * np.pi * hour / 24)

dow = hourly.index.dayofweek
hourly["dow_sin"] = np.sin(2 * np.pi * dow / 7)
hourly["dow_cos"] = np.cos(2 * np.pi * dow / 7)

month = hourly.index.month
hourly["month_sin"] = np.sin(2 * np.pi * month / 12)
hourly["month_cos"] = np.cos(2 * np.pi * month / 12)

hourly["is_weekend"] = (hourly.index.dayofweek >= 5).astype(int)

In [6]:
hourly.head()

,Global_active_power_mean,Global_active_power_max,Global_active_power_min,Global_active_power_std,Voltage_mean,Voltage_max,Voltage_min,Voltage_std,Global_intensity_mean,Global_intensity_max,...,Sub_metering_3_max,Sub_metering_3_min,Sub_metering_3_std,hour_sin,hour_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend
Datetime,,,,,,,,,,,,,,,,,,,,,
2006-12-16 17:00:00,4.188278,7.026,2.472,1.070610,234.643889,237.14,230.98,1.528529,18.100000,33.2,...,18.0,16.0,0.424451,-0.965926,-2.588190e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1
2006-12-16 18:00:00,3.598283,6.752,2.188,1.132717,234.580167,238.28,231.85,1.623576,15.600000,29.0,...,18.0,16.0,0.468198,-1.000000,-1.836970e-16,-0.974928,-0.222521,-2.449294e-16,1.0,1
2006-12-16 19:00:00,3.400233,4.070,3.202,0.135354,233.232500,235.12,231.57,0.901678,14.503333,17.4,...,17.0,16.0,0.469102,-0.965926,2.588190e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1
2006-12-16 20:00:00,3.268567,3.496,1.832,0.264286,234.071500,237.54,231.95,1.483866,13.916667,14.8,...,18.0,16.0,0.454420,-0.866025,5.000000e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1
2006-12-16 21:00:00,3.056467,3.502,1.692,0.576796,237.158667,239.69,235.73,0.862382,13.046667,14.8,...,18.0,17.0,0.415450,-0.707107,7.071068e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1

In [7]:
target_col = "Global_active_power_mean"

hourly["lag_1"] = hourly[target_col].shift(1)
hourly["lag_24"] = hourly[target_col].shift(24)
hourly["lag_168"] = hourly[target_col].shift(168)

hourly.head()

,Global_active_power_mean,Global_active_power_max,Global_active_power_min,Global_active_power_std,Voltage_mean,Voltage_max,Voltage_min,Voltage_std,Global_intensity_mean,Global_intensity_max,...,hour_sin,hour_cos,dow_sin,dow_cos,month_sin,month_cos,is_weekend,lag_1,lag_24,lag_168
Datetime,,,,,,,,,,,,,,,,,,,,,
2006-12-16 17:00:00,4.188278,7.026,2.472,1.070610,234.643889,237.14,230.98,1.528529,18.100000,33.2,...,-0.965926,-2.588190e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1,NaN,NaN,NaN
2006-12-16 18:00:00,3.598283,6.752,2.188,1.132717,234.580167,238.28,231.85,1.623576,15.600000,29.0,...,-1.000000,-1.836970e-16,-0.974928,-0.222521,-2.449294e-16,1.0,1,4.188278,NaN,NaN
2006-12-16 19:00:00,3.400233,4.070,3.202,0.135354,233.232500,235.12,231.57,0.901678,14.503333,17.4,...,-0.965926,2.588190e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1,3.598283,NaN,NaN
2006-12-16 20:00:00,3.268567,3.496,1.832,0.264286,234.071500,237.54,231.95,1.483866,13.916667,14.8,...,-0.866025,5.000000e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1,3.400233,NaN,NaN
2006-12-16 21:00:00,3.056467,3.502,1.692,0.576796,237.158667,239.69,235.73,0.862382,13.046667,14.8,...,-0.707107,7.071068e-01,-0.974928,-0.222521,-2.449294e-16,1.0,1,3.268567,NaN,NaN

In [8]:
for window in [6, 24, 168]:
    hourly[f"roll_mean_{window}h"] = (
        hourly[target_col]
        .shift(1)
        .rolling(window)
        .mean()
    )

    hourly[f"roll_std_{window}h"] = (
        hourly[target_col]
        .shift(1)
        .rolling(window)
        .std()
    )

hourly[[
    "lag_1", "lag_24", "lag_168",
    "roll_mean_6h", "roll_std_6h",
    "roll_mean_24h", "roll_std_24h",
    "roll_mean_168h", "roll_std_168h",
]].head(200)

,lag_1,lag_24,lag_168,roll_mean_6h,roll_std_6h,roll_mean_24h,roll_std_24h,roll_mean_168h,roll_std_168h
Datetime,,,,,,,,,
2006-12-16 17:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 18:00:00,4.188278,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 19:00:00,3.598283,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 20:00:00,3.400233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2006-12-16 21:00:00,3.268567,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
2006-12-24 20:00:00,0.454033,4.181400,3.361500,1.520206,0.993939,2.396708,1.218747,1.768344,1.223219
2006-12-24 21:00:00,0.474100,3.288433,3.040767,1.370633,1.084211,2.242237,1.217652,1.751157,1.220983
2006-12-24 22:00:00,0.484033,4.215850,1.518000,0.935167,0.713594,2.125387,1.247094,1.735938,1.220746
2006-12-24 23:00:00,0.479767,5.254217,0.437733,0.680606,0.493061,1.969717,1.207352,1.729759,1.224478
2006-12-25 00:00:00,0.486333,4.028000,0.276367,0.480578,0.016725,1.771055,1.021345,1.730048,1.224177

In [9]:
hourly = hourly.dropna()
hourly.head()

,Global_active_power_mean,Global_active_power_max,Global_active_power_min,Global_active_power_std,Voltage_mean,Voltage_max,Voltage_min,Voltage_std,Global_intensity_mean,Global_intensity_max,...,is_weekend,lag_1,lag_24,lag_168,roll_mean_6h,roll_std_6h,roll_mean_24h,roll_std_24h,roll_mean_168h,roll_std_168h
Datetime,,,,,,,,,,,,,,,,,,,,,
2006-12-23 17:00:00,5.429683,7.164,2.984,1.192589,233.644167,236.25,231.17,1.311882,23.360000,30.4,...,1,4.326733,1.496800,4.188278,3.607728,0.539234,2.931298,0.983724,1.762654,1.143968
2006-12-23 18:00:00,3.879400,5.270,1.666,0.886704,238.000500,240.59,235.57,1.222337,16.363333,22.4,...,1,5.429683,2.686967,3.598283,3.986175,0.861707,3.095168,1.059062,1.770044,1.163571
2006-12-23 19:00:00,4.117833,5.392,2.036,0.831345,238.729333,242.24,235.69,1.477832,17.300000,22.8,...,1,3.879400,3.938167,3.400233,4.144608,0.700778,3.144853,1.067020,1.771717,1.166414
2006-12-23 20:00:00,4.181400,6.230,2.366,0.850218,238.518833,242.02,236.01,1.235284,17.596667,26.2,...,1,4.117833,3.536067,3.268567,4.263197,0.604431,3.152339,1.073439,1.775988,1.173705
2006-12-23 21:00:00,3.288433,5.352,1.390,1.035213,238.594667,241.65,234.89,1.450798,13.893333,22.8,...,1,4.181400,4.451267,3.056467,4.333769,0.556460,3.179228,1.091401,1.781422,1.182734

In [10]:
hourly.columns

Index(['Global_active_power_mean', 'Global_active_power_max',
       'Global_active_power_min', 'Global_active_power_std', 'Voltage_mean',
       'Voltage_max', 'Voltage_min', 'Voltage_std', 'Global_intensity_mean',
       'Global_intensity_max', 'Global_intensity_min', 'Global_intensity_std',
       'Sub_metering_1_mean', 'Sub_metering_1_max', 'Sub_metering_1_min',
       'Sub_metering_1_std', 'Sub_metering_2_mean', 'Sub_metering_2_max',
       'Sub_metering_2_min', 'Sub_metering_2_std', 'Sub_metering_3_mean',
       'Sub_metering_3_max', 'Sub_metering_3_min', 'Sub_metering_3_std',
       'hour_sin', 'hour_cos', 'dow_sin', 'dow_cos', 'month_sin', 'month_cos',
       'is_weekend', 'lag_1', 'lag_24', 'lag_168', 'roll_mean_6h',
       'roll_std_6h', 'roll_mean_24h', 'roll_std_24h', 'roll_mean_168h',
       'roll_std_168h'],
      dtype='str')

In [11]:
target = "Global_active_power_mean"

time_feats = [
    "hour_sin", "hour_cos",
    "dow_sin", "dow_cos",
    "month_sin", "month_cos",
    "is_weekend"
]

electrical_feats = [
    col for col in hourly.columns
    if "Voltage" in col
    or "Sub_metering" in col
    or "Global_intensity" in col
]

lag_feats = [
    "lag_1", "lag_24", "lag_168",
    "roll_mean_6h", "roll_std_6h",
    "roll_mean_24h", "roll_std_24h",
    "roll_mean_168h", "roll_std_168h"
]

F1 = [target]
F2 = F1 + time_feats
F3 = F2 + electrical_feats
F4 = F3 + lag_feats

len(F1), len(F2), len(F3), len(F4)

(1, 8, 28, 37)

In [12]:
import json

feature_sets = {
    "F1": F1,
    "F2": F2,
    "F3": F3,
    "F4": F4,
}

with open("feature_sets.json", "w") as f:
    json.dump(feature_sets, f, indent=2)

print("Saved feature_sets.json")

Saved feature_sets.json

In [13]:
hourly.to_csv("final.csv")